#!/bin/bash
# -*- ENCODING: UTF-8 -*-

#
#-----------------------------------------------------------------------------------
# 
# Installs a basic setup based in PHP 7.4 for Debian / Ubuntu distros. 
# [David Rodríguez, @davidjguru] [davidjguru@solucionex.com]
# Title: PHP 7.4 Basic Setup
# Description: Installs PHP related packages from the command line. 
#
# davidjguru@gmail.com
# https://www.therussianlullaby.com
# https://www.solucionex.com
#-----------------------------------------------------------
#

sudo apt -yqq update &&
sudo apt -yqq upgrade && 
sudo apt -yqq install   \  
php7.4 		          \
php7.4-bcmath           \
php7.4-bz2              \
php7.4-curl 		      \
php7.4-dev 		      \
php7.4-gd 		      \
php7.4-dom		      \
php7.4-imap             \
php7.4-imagick          \
php7.4-intl 		      \
php7.4-json 		      \
php7.4-ldap 		      \
php7.4-mbstring	      \
php7.4-mysql		      \
php7.4-oauth		      \
php7.4-odbc		      \
php7.4-uploadprogress   \
php7.4-ssh2		      \
php7.4-xml		      \
php7.4-yaml		      \
php7.4-zip		      \
php7.4-solr		      \
php7.4-apcu		      \
php7.4-opcache	      \
php7.4-redis		      \
php7.4-memcache 	      \
php7.4-memcached 	      \
php7.4-xdebug	          \
php7.4-sqlite3          
