#!/bin/bash
# -*- ENCODING: UTF-8 -*-
#
#
#-----------------------------------------------------------------------------------
# 
# Installs Docker, Docker-Compose and Lando in Ubuntu.
# [David Rodríguez, @davidjguru] [davidjguru@solucionex.com]
# Title: installing_docker_dockercompose_lando
# Description: Installs the last available versions for Docker, Docker-Compose and Lando. 
#
# davidjguru@gmail.com
# https://www.therussianlullaby.com
# https://www.solucionex.com
#-----------------------------------------------------------
#

## Update the list of packages.
echo -e "   \e[1;4;31mUpdate the package list...\e[0m"
sudo apt  update

# Installs some basic resources in your System (Ubuntu).
echo -e "   \e[1;4;31mInstalling some basic resources for your system...\e[0m"
sudo apt install -y build-essential apt-transport-https ca-certificates jq curl software-properties-common file git  gnupg-agent

# Sets the Docker official repository. 
echo -e "   \e[1;4;31mSetting the Docker repository...\e[0m"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update

# Installs the Docker basic packages.
echo -e "   \e[1;4;31mInstalling sthe Docker related packages...\e[0m"
sudo apt install docker-ce docker-ce-cli containerd.io

# Enables Docker.
echo -e "   \e[1;4;31mEnabling Docker Engine...\e[0m"
sudo systemctl unmask docker
sudo systemctl start docker
sudo systemctl enable --now docker

# Adds the current user to the Docker group.
echo -e "   \e[1;4;31mAdding your current user to the new Docker group.\e[0m"
sudo usermod -aG docker $USER

# Grants permissions over the Docker system for users.
echo -e "   \e[1;4;31mGrants permissions over the Docker system.\e[0m"
sudo chmod 666 /var/run/docker*

# Tests if Docker is running or not.
echo -e "   \e[1;4;31mDocker has been installed in your system. Currently Docker is: \e[0m"
systemctl is-active docker

# Checks if Docker is ready.
echo -e "   \e[1;4;31mThis is your current Docker version: \e[0m"
docker --version

# Verifies Docker running.
echo -e "   \e[1;4;31mWe're running a Docker initial testing - hello world -> \e[0m"
docker run hello-world

# Installs Docker Compose.
echo -e "   \e[1;4;31mInstalling Docker Compose:    \e[0m"
sudo apt install -y docker-compose

# Checks if Docker Compose was installed and gets the current version.
echo -e "   \e[1;4;31mDocker Compose has been installed in your system: \e[0m"
docker-compose --version

# Downloads and executes the Lando .deb package.
echo -e "   \e[1;4;31mDownloading and installing Lando package...\e[0m"
wget https://files.devwithlando.io/lando-stable.deb
sudo dpkg -i lando-stable.deb